// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Gameapp.Models;


#nullable disable

namespace Gameapp.Data
{
    public partial class GamesContext : DbContext
    {
        public GamesContext()
        {
        }

        public GamesContext(DbContextOptions<GamesContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AddressType> AddressType { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<BestOffer> BestOffer { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<ChampionShip> ChampionShip { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Coupon> Coupon { get; set; }
        public virtual DbSet<CouponType> CouponType { get; set; }
        public virtual DbSet<Curreny> Curreny { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<ItemsOrderTable2> ItemsOrderTable2 { get; set; }
        public virtual DbSet<ItemsOrderTb> ItemsOrderTb { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<PageContent> PageContent { get; set; }
        public virtual DbSet<PaymentMehod> PaymentMehod { get; set; }
        public virtual DbSet<ProductImages> ProductImages { get; set; }
        public virtual DbSet<ShippingAddress> ShippingAddress { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<SliderType> SliderType { get; set; }
        public virtual DbSet<SubCategory> SubCategory { get; set; }
        public virtual DbSet<WishList> WishList { get; set; }
        public virtual DbSet<ContactUS> ContactUs { get; set; }
        public virtual DbSet<FAQ> FAQ { get; set; }
        public virtual DbSet<SoicialMidiaLink> SoicialMidiaLink { get; set; }
        public virtual DbSet<Champion> Champions { get; set; }
        public virtual DbSet<Platform> Platforms { get; set; }

        //public virtual DbSet<CustomerFavourite> CustomerFavourites { get; set; }
        public virtual DbSet<CustomerPlatsGamesFavourite> CustomerPlatsGamesFavourite { get; set; }
        public virtual DbSet<ChampionSlider> ChampionSliders { get; set; }
        public virtual DbSet<ChampionGroup> ChampionGroups { get; set; }
        public virtual DbSet<ChampionGroupList> ChampionGroupLists { get; set; }
        public virtual DbSet<PlatformGame> PlatformGames { get; set; }
        public virtual DbSet<GameMode> GameModes { get; set; }
        public virtual DbSet<ParticipState> ParticipStates { get; set; }
        public virtual DbSet<ChampionParticipate> ChampionParticipates { get; set; }
        public virtual DbSet<ChampionSchedule> ChampionSchedules { get; set; }
        public virtual DbSet<ChampionBanner> ChampionBanners { get; set; }
        public virtual DbSet<ChampionType> ChampionType { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Collection> Collections { get; set; }
        public virtual DbSet<CollectionItem> CollectionItems { get; set; }
        public virtual DbSet<Newsletter> Newsletter { get; set; }
        public virtual DbSet<ContactUsMessages> ContactUsMessages { get; set; }
        public virtual DbSet<Subscriptions> Subscriptions { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<PublicDevice> PublicDevices { get; set; }
        public virtual DbSet<PublicNotification> PublicNotifications { get; set; }
        public virtual DbSet<PublicNotificationDevice> PublicNotificationDevices { get; set; }



        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<ItemsOrderTable2>().HasKey(table => new {
                table.OrderId,
                table.ItemId
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}