// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    public partial class AddressType
    {
        public AddressType()
        {
            ShippingAddress = new HashSet<ShippingAddress>();
        }

        [Key]
        public int AddressTypeId { get; set; }
        [Column("AddressType")]
        [StringLength(50)]
        public string AddressType1 { get; set; }

        [InverseProperty("AddressType")]
        public virtual ICollection<ShippingAddress> ShippingAddress { get; set; }
    }
}