// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    public partial class Banner
    {
        [Key]
        public int BannerId { get; set; }

        public string Pic { get; set; }
        public bool? IsActive { get; set; }

        [Required]
        public int? OrderIndex { get; set; }

        [Required]

        public int? SliderTypeId { get; set; }
        [Column("EntityID")]
        [StringLength(50)]


        public string EntityId { get; set; }

        [NotMapped]
        [Required]
        public IFormFile Picture { get; set; }


        public int? CountryId { get; set; }

        [ForeignKey("CountryId")]
        public Country Country { get; set; }
        public virtual SliderType HomeSliderType { get; set; }

    }
}