// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    public partial class ChampionShip
    {
        [Key]
        public int ChampionshipId { get; set; }
        [StringLength(50)]
        public string ChampionshipName { get; set; }
        public string ChampionshipPhoto { get; set; }
    }
}