// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    public partial class Country
    {
        [Key]
        public int CountryId { get; set; }
        [Column("CountryTLAR")]
        [StringLength(50)]
        [Required]
        public string CountryTlar { get; set; }
        [Column("CountryTLEN")]
        [StringLength(50)]
        [Required]

        public string CountryTlen { get; set; }
        //[Required]
        public string Pic { get; set; }
        public bool? IsActive { get; set; }

        [Required]

        public int? OrderIndex { get; set; }
    }
}