// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    public partial class CouponType
    {
        public CouponType()
        {
            Coupon = new HashSet<Coupon>();
        }

        [Key]
        public int Id { get; set; }
        public string Title { get; set; }

        [InverseProperty("CouponType")]
        public virtual ICollection<Coupon> Coupon { get; set; }
    }
}