// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    public partial class Curreny
    {
        [Key]
        public int CurrenyId { get; set; }
        [Column("CurrenyTLAR")]
        [StringLength(50)]
        [Required]
        public string CurrenyTlar { get; set; }
        [Column("CurrenyTLEN")]
        [StringLength(50)]
        [Required]

        public string CurrenyTlen { get; set; }
        [Required]

        public string CurrencyPic { get; set; }
        public bool? IsActive { get; set; }
    }
}