// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    public partial class Customer
    {
        public Customer()
        {
            Items = new HashSet<Items>();
            Order = new HashSet<Order>();
            ShippingAddress = new HashSet<ShippingAddress>();
            ShoppingCart = new HashSet<ShoppingCart>();
            WishList = new HashSet<WishList>();
        }

        [Key]
        public int CustomerId { get; set; }
        [Column("CustomernameAR")]
        [StringLength(50)]
        public string CustomernameAr { get; set; }
        [Column("CustomernameEN")]
        [StringLength(50)]
        public string CustomernameEn { get; set; }
        [StringLength(50)]
        public string CustomerAddress { get; set; }
        [StringLength(50)]
        public string Customerphone { get; set; }
        [StringLength(50)]
        public string CustomerEmail { get; set; }
        [StringLength(10)]
        public string FavouriteItem { get; set; }

        public DateTime RegisterDate { get; set; }


        public string CustomerImage { get; set; }
        //public bool? IsFavourite { get; set; }

        [InverseProperty("Customer")]
        public virtual ICollection<Items> Items { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<Order> Order { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<ShippingAddress> ShippingAddress { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<WishList> WishList { get; set; }

        //[ForeignKey("FavPlatform")]
        //public int? FavPlatformId { get; set; }
        //public virtual Platform FavPlatform { get; set; }
    }
}