// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    [Index(nameof(ItemId1), Name = "IX_ItemsOrderTb_ItemId1")]
    [Index(nameof(OrderId), Name = "IX_ItemsOrderTb_OrderId")]
    public partial class ItemsOrderTb
    {
        [Key]
        public int ItemId { get; set; }
        public int OrderId { get; set; }
        public int ItemId1 { get; set; }
        public int Quantity { get; set; }

        [ForeignKey(nameof(ItemId1))]
        [InverseProperty(nameof(Items.ItemsOrderTb))]
        public virtual Items ItemId1Navigation { get; set; }
        [ForeignKey(nameof(OrderId))]
        [InverseProperty("ItemsOrderTb")]
        public virtual Order Order { get; set; }
    }
}