// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Gameapp.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    [Index(nameof(CustomerId), Name = "IX_Order_CustomerId")]
    [Index(nameof(ItemsItemId), Name = "IX_Order_ItemsItemId")]
    [Index(nameof(PaymentMehodPaymentMethodId), Name = "IX_Order_PaymentMehodPaymentMethodId")]
    public partial class Order
    {
        public Order()
        {
            ItemsOrderTable2 = new HashSet<ItemsOrderTable2>();
            ItemsOrderTb = new HashSet<ItemsOrderTb>();
        }

        [Key]
        public int OrderId { get; set; }
        public DateTime OrderDate { get; set; }
        public string OrderSerial { get; set; }
        public int? CustomerId { get; set; }
        public int? ShippingAddressId { get; set; }

        [ForeignKey("ShippingAddressId")]
        public ShippingAddress ShippingAddress { get; set; }
        public bool? IsDeliverd { get; set; }
        [Column("notes")]
        [StringLength(50)]
        public string Notes { get; set; }
        public int? OrderIndex { get; set; }
        public int? PaymentMehodPaymentMethodId { get; set; }
        public int? ItemsItemId { get; set; }
        public int ShopId { get; set; }

        public float OrderTotal { get; set; }

        public float OrderDiscount { get; set; }
        public int? CouponId { get; set; }
        public bool ispaid { get; set; }


        [ForeignKey(nameof(CouponId))]
        public Coupon Coupon { get; set; }

        public int? CouponTypeId { get; set; }

        [ForeignKey(nameof(CouponTypeId))]
        public CouponType CouponType { get; set; }
        public int uniqeId { get; set; }
        public float? CouponAmount { get; set; }
        public float? Deliverycost { get; set; }
        public float? OrderNet { get; set; }


        [ForeignKey(nameof(CustomerId))]
        [InverseProperty("Order")]
        public virtual Customer Customer { get; set; }
        [ForeignKey(nameof(ItemsItemId))]
        [InverseProperty(nameof(Items.Order))]
        public virtual Items ItemsItem { get; set; }
        [ForeignKey(nameof(PaymentMehodPaymentMethodId))]
        [InverseProperty(nameof(PaymentMehod.Order))]
        public virtual PaymentMehod PaymentMehodPaymentMethod { get; set; }
        [InverseProperty("Order")]
        public virtual ICollection<ItemsOrderTable2> ItemsOrderTable2 { get; set; }
        [InverseProperty("Order")]
        public virtual ICollection<ItemsOrderTb> ItemsOrderTb { get; set; }

        [ForeignKey("ShopId")]
        public virtual Shop shop { get; set; }


        [NotMapped]
        public IEnumerable<OrderItemsList> GetOrderModel { get; set; }

        public string payment_type { get; set; }
        public string PaymentID { get; set; }
        public string Result { get; set; }
        public DateTime? PostDate { get; set; }
        public string TranID { get; set; }
        public string Ref { get; set; }
        public string TrackID { get; set; }
        public string Auth { get; set; }
    }
}