// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    public partial class PageContent
    {
        [Key]
        public int Id { get; set; }

        [Required]

        public string PageTitle { get; set; }

        [Required]

        public string Content { get; set; }
    }
}