// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    public partial class PaymentMehod
    {
        public PaymentMehod()
        {
            Order = new HashSet<Order>();
        }

        [Key]
        [Column("PaymentMethodID")]
        public int PaymentMethodId { get; set; }
        [StringLength(50)]
        public string PaymentMethodName { get; set; }
        public string PaymentMethodPic { get; set; }
        public bool IsActive { get; set; }

        [InverseProperty("PaymentMehodPaymentMethod")]
        public virtual ICollection<Order> Order { get; set; }
    }
}