// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    [Index(nameof(AddressTypeId), Name = "IX_ShippingAddress_AddressTypeId")]
    [Index(nameof(CustomerId), Name = "IX_ShippingAddress_CustomerId")]
    public partial class ShippingAddress
    {
        [Key]
        public int ShippingAddressId { get; set; }
        public int? CustomerId { get; set; }
        [StringLength(50)]
        public string AddressNickname { get; set; }
        [StringLength(50)]
        public string Area { get; set; }
        public int? AddressTypeId { get; set; }
        [Required]
        [StringLength(50)]
        public string Street { get; set; }
        [StringLength(50)]
        public string Block { get; set; }
        [StringLength(50)]
        public string Avenue { get; set; }
        [StringLength(50)]
        public string Building { get; set; }
        [StringLength(50)]
        public string Floor { get; set; }
        [StringLength(50)]
        public string Office { get; set; }
        [StringLength(50)]
        public string AdditionalDirection { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        [ForeignKey(nameof(AddressTypeId))]
        [InverseProperty("ShippingAddress")]
        public virtual AddressType AddressType { get; set; }
        [ForeignKey(nameof(CustomerId))]
        [InverseProperty("ShippingAddress")]
        public virtual Customer Customer { get; set; }
    }
}