// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    [Index(nameof(CustomerId), Name = "IX_ShoppingCart_CustomerId")]
    [Index(nameof(ItemId), Name = "IX_ShoppingCart_ItemId")]
    public partial class ShoppingCart
    {
        [Key]
        public int ShoppingCartId { get; set; }
        public int? CustomerId { get; set; }
        public int? ItemId { get; set; }
        [StringLength(50)]
        public float ItemPrice { get; set; }
        public int ItemQty { get; set; }
        public float ItemTotal { get; set; }

        public float Deliverycost { get; set; }

        [ForeignKey(nameof(CustomerId))]
        [InverseProperty("ShoppingCart")]
        public virtual Customer Customer { get; set; }

        [ForeignKey(nameof(ItemId))]
        public virtual Items Item { get; set; }
    }
}