// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    public partial class SliderType
    {
        public SliderType()
        {
            Slider = new HashSet<Slider>();
        }

        [Key]
        public int SliderTypeId { get; set; }
        [Column("SliderTypeTLAR")]
        [StringLength(50)]
        public string SliderTypeTlar { get; set; }
        [Column("SliderTypeTLEN")]
        [StringLength(50)]
        public string SliderTypeTlen { get; set; }

        [InverseProperty("SliderType")]
        public virtual ICollection<Slider> Slider { get; set; }
        public virtual ICollection<Banner> Banner { get; set; }

    }
}