// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    [Index(nameof(SliderTypeId), Name = "IX_Slider_SliderTypeId")]
    public partial class Slider
    {
        [Key]
        public int SliderId { get; set; }

        public string Pic { get; set; }
        public bool? IsActive { get; set; }
        [Required]
        public int? SliderTypeId { get; set; }
        [Column("EntityID")]
        

        public string EntityId { get; set; }

        [Required]

        public int? OrderIndex { get; set; }

        [ForeignKey(nameof(SliderTypeId))]
        [InverseProperty("Slider")]
        public virtual SliderType SliderType { get; set; }

        public int? CountryId { get; set; }

        [ForeignKey("CountryId")]
        public Country Country { get; set; }
    }
}