// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Gameapp.Models
{
    [Index(nameof(CustomerId), Name = "IX_WishList_CustomerId")]
    [Index(nameof(ItemId), Name = "IX_WishList_ItemId")]
    public partial class WishList
    {
        [Key]
        public int WishlistId { get; set; }
        public int? CustomerId { get; set; }
        public int? ItemId { get; set; }
       

        [ForeignKey(nameof(CustomerId))]
        [InverseProperty("WishList")]
        public virtual Customer Customer { get; set; }
        [InverseProperty("WishList")]
        public virtual Shop Shop { get; set; }
        public virtual Items Item { get; set; }
       
    }
}